package org.automerge.repo;

import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutionException;
import org.automerge.LoadLibrary;

/**
 * Repository for managing Automerge documents with networking and storage.
 *
 * Use {@link #load(RepoConfig)} to create a Repo instance. If storage is empty,
 * a new repository will be initialized.
 *
 * <p>
 * This class implements {@link AutoCloseable} to support try-with-resources:
 *
 * <pre>{@code
 * try (Repo repo = Repo.load(config)) {
 *     // Use the repository
 * } // Automatically closed
 * }</pre>
 */
public class Repo implements AutoCloseable {
    static {
        LoadLibrary.initialize();
    }

    private final RepoRuntime runtime;
    private final ConcurrentHashMap<DocumentId, DocHandle> documents;

    private Repo(RepoRuntime runtime) {
        this.runtime = runtime;
        this.documents = new ConcurrentHashMap<>();
    }

    /**
     * Loads a repository from storage.
     *
     * @param config
     *               The repository configuration
     * @return A loaded Repo instance
     * @throws RuntimeException
     *                          if loading fails
     */
    public static Repo load(RepoConfig config) {
        LoadLibrary.initialize();

        // Create the loader
        RepoSys.SamodLoaderPointer loaderPointer = RepoSys.createSamodLoader(config.getPeerId().toString());
        RepoLoader loader = new RepoLoader(loaderPointer);

        try {
            // Loop until loading is complete
            while (true) {
                long now = System.currentTimeMillis();
                LoaderStepResult result = loader.step(now);

                if (result instanceof LoaderStepResult.Loaded) {
                    // Loading complete - extract the hub pointer and create runtime
                    LoaderStepResult.Loaded loaded = (LoaderStepResult.Loaded) result;
                    RepoRuntime runtime = new RepoRuntime(loaded.getHub(), config);
                    runtime.start();

                    return new Repo(runtime);
                } else if (result instanceof LoaderStepResult.NeedIo) {
                    // Execute storage tasks and provide results back
                    LoaderStepResult.NeedIo needIo = (LoaderStepResult.NeedIo) result;
                    java.util.List<IoTask<StorageTask>> ioTasks = needIo.getIoTasks();

                    for (IoTask<StorageTask> ioTask : ioTasks) {
                        StorageTask task = ioTask.getAction();
                        StorageResult storageResult = executeStorageTask(config.getStorage(), task);
                        IoResult<StorageResult> ioResult = new IoResult<StorageResult>(ioTask.getTaskId(),
                                storageResult);
                        loader.provideIoResult(ioResult);
                    }
                } else {
                    throw new IllegalStateException("Unknown LoaderStepResult type: " + result);
                }
            }
        } catch (Exception e) {
            // Clean up on failure
            loader.free();
            throw new RuntimeException("Failed to load repository", e);
        }
    }

    /**
     * Loads a repository with default configuration.
     *
     * @return a new Repo instance with in memory storage, an autogenerated peer
     *         ID, and an allow all announce policy
     */
    public static Repo load() {
        RepoConfig config = RepoConfig.builder().build();
        return Repo.load(config);
    }

    /**
     * Executes a storage task and returns the result.
     */
    private static StorageResult executeStorageTask(Storage storage, StorageTask task) {
        try {
            if (task instanceof StorageTask.Load) {
                StorageTask.Load load = (StorageTask.Load) task;
                byte[] value = storage.load(load.getKey()).get().orElse(null);
                return new StorageResult.Load(value);
            } else if (task instanceof StorageTask.LoadRange) {
                StorageTask.LoadRange loadRange = (StorageTask.LoadRange) task;
                java.util.Map<StorageKey, byte[]> items = storage.loadRange(loadRange.getPrefix()).get();
                return new StorageResult.LoadRange(items);
            } else if (task instanceof StorageTask.Put) {
                StorageTask.Put put = (StorageTask.Put) task;
                storage.put(put.getKey(), put.getValue()).get();
                return new StorageResult.Put();
            } else if (task instanceof StorageTask.Delete) {
                StorageTask.Delete delete = (StorageTask.Delete) task;
                storage.delete(delete.getKey()).get();
                return new StorageResult.Delete();
            } else {
                throw new IllegalArgumentException("Unknown StorageTask type: " + task);
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException("Interrupted while executing storage task", e);
        } catch (ExecutionException e) {
            throw new RuntimeException(
                    "Storage operation failed: " + (e.getCause() != null ? e.getCause().getMessage() : e.getMessage()),
                    e.getCause() != null ? e.getCause() : e);
        }
    }

    /**
     * Creates a new empty document.
     *
     * @return A CompletableFuture that completes with a DocHandle for the new
     *         document
     */
    public CompletableFuture<DocHandle> create() {
        org.automerge.Document doc = new org.automerge.Document();
        byte[] content = doc.save();
        return create(content);
    }

    /**
     * Creates a new document with initial content.
     *
     * @param initialContent
     *                       Serialized Automerge document bytes
     * @return A CompletableFuture that completes with a DocHandle for the new
     *         document
     */
    public CompletableFuture<DocHandle> create(byte[] initialContent) {
        if (initialContent == null || initialContent.length == 0) {
            throw new IllegalArgumentException(
                    "initialContent cannot be null or empty. Use create() for empty documents.");
        }
        return runtime.createDocument(initialContent).thenApply(result -> {
            DocumentId docId = result.getDocumentId();
            DocumentActorId actorId = result.getActorId();
            AutomergeUrl url = new AutomergeUrl(docId);
            DocHandle handle = new DocHandle(runtime, docId, actorId, url);

            DocHandle existing = documents.putIfAbsent(docId, handle);
            if (existing != null) {
                throw new IllegalStateException("Document already exists with ID: " + docId);
            }

            return handle;
        });
    }

    /**
     * Finds an existing document by its ID.
     *
     * @param documentId
     *                   The document ID to find
     * @return A CompletableFuture that completes with a DocHandle if found, or
     *         Optional.empty() if not found
     */
    public CompletableFuture<Optional<DocHandle>> find(DocumentId documentId) {
        DocHandle existing = documents.get(documentId);
        if (existing != null) {
            return CompletableFuture.completedFuture(Optional.of(existing));
        }

        return runtime.findDocument(documentId).thenApply(result -> {
            if (!result.isFound()) {
                return Optional.empty();
            }

            DocumentActorId actorId = result.getActorId();
            AutomergeUrl url = new AutomergeUrl(documentId);
            DocHandle handle = new DocHandle(runtime, documentId, actorId, url);

            DocHandle racingHandle = documents.putIfAbsent(documentId, handle);
            return Optional.of(racingHandle != null ? racingHandle : handle);
        });
    }

    /**
     * Finds an existing document by its Automerge URL.
     *
     * @param url
     *            The Automerge URL
     * @return A CompletableFuture that completes with a DocHandle if found, or null
     */
    public CompletableFuture<Optional<DocHandle>> find(AutomergeUrl url) {
        return find(url.getId());
    }

    /**
     * Registers a dialer for outbound connections with automatic reconnection.
     *
     * @param dialer
     *               The user's Dialer implementation for creating transports
     * @return A DialerHandle representing the registered dialer
     */
    public DialerHandle dial(Dialer dialer) {
        return runtime.addDialer(dialer, DialerConfig.defaults());
    }

    /**
     * Registers a dialer for outbound connections with automatic reconnection.
     *
     * @param config
     *               The dialer configuration (URL and backoff settings)
     * @param dialer
     *               The user's Dialer implementation for creating transports
     * @return A DialerHandle representing the registered dialer
     */
    public DialerHandle dial(Dialer dialer, DialerConfig config) {
        return runtime.addDialer(dialer, config);
    }

    /**
     * Creates an acceptor for inbound connections.
     *
     * @param url
     *            The URL identifying this listener endpoint
     * @return An AcceptorHandle for accepting inbound connections
     */
    public AcceptorHandle makeAcceptor(String url) {
        return runtime.makeAcceptor(url);
    }

    /**
     * Stops the repository runtime gracefully.
     */
    public void stop() {
        runtime.stop();
    }

    /**
     * Closes the repository and frees all resources.
     */
    @Override
    public void close() {
        runtime.close();
    }

    public PeerId getPeerId() {
        return runtime.getPeerId();
    }
}
